name: Code Checker with Super-Linter

on:
  pull_request:
    branches:
      - main # Adjust the branch name as needed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Use the desired Node.js version

      - name: Install dependencies
        run: npm install # You can also use yarn if preferred

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: "true" # Set to "true" if you want to validate all files
          DEFAULT_BRANCH: "master" # Replace with your default branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

